apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
spec:
  replicas: 2 # Lance deux copies de votre app pour la sécurité
  selector:
    matchLabels:
      app: php-web
  template:
    metadata:
      labels:
        app: php-web
    spec:
      containers:
      - name: php-container
        image: aminebg10/projet-devops-php:latest # Votre image Docker Hub
        ports:
        - containerPort: 80