apiVersion: apps/v1
kind: Deployment
metadata:
  name: amine-app-deployment
  labels:
    app: amine-devops
spec:
  replicas: 2 # Haute disponibilité avec 2 instances
  selector:
    matchLabels:
      app: amine-devops
  template:
    metadata:
      labels:
        app: amine-devops
    spec:
      containers:
      - name: amine-app # Nom validé via kubectl
        image: aminebg10/amine-devops-app:latest
        ports:
        - containerPort: 80